# Generated by Django 4.1.3 on 2022-12-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0021_remove_givenanswer_related_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='test.png', null=True, upload_to='uploads/'),
        ),
    ]
