# Generated by Django 4.1.3 on 2023-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0024_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/common_tasks/'),
        ),
    ]
