# Generated by Django 4.1.3 on 2023-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0031_remove_teacher_subject_subject_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeredcommontask",
            name="finished_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="answeredinfotask",
            name="finished_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="takentest",
            name="finished_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
