# Generated by Django 4.1.3 on 2023-01-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0033_remove_answeredinfotask_was_checked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeredcommontask",
            name="comment_from_teacher",
            field=models.TextField(blank=True, default=""),
        ),
    ]
