# Generated by Django 4.1.3 on 2023-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0038_remove_answeredcommontask_was_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_pictures/%Y/%m"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile_pictures/%Y/%m"
            ),
        ),
        migrations.AlterField(
            model_name="answeredcommontask",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("DONE", "Done"),
                    ("PASSED", "Passed"),
                    ("EVALUATED", "Evaluated"),
                    ("CHECKED", "CHECKED"),
                ],
                default="ASSIGNED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="answeredinfotask",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("DONE", "Done"),
                    ("PASSED", "Passed"),
                    ("EVALUATED", "Evaluated"),
                    ("CHECKED", "CHECKED"),
                ],
                default="ASSIGNED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="takentest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("DONE", "Done"),
                    ("PASSED", "Passed"),
                    ("EVALUATED", "Evaluated"),
                    ("CHECKED", "CHECKED"),
                ],
                default="ASSIGNED",
                max_length=255,
            ),
        ),
    ]
