# Generated by Django 4.1.3 on 2023-01-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0039_student_profile_picture_teacher_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                default="student.jpg",
                null=True,
                upload_to="uploads/profile_pictures/%Y/",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                default="teacher.jpg",
                null=True,
                upload_to="uploads/profile_pictures/%Y/",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "doc",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/documents/"
                    ),
                ),
                (
                    "st_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="univ_app.stgroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="univ_app.student",
                    ),
                ),
            ],
        ),
    ]
