# Generated by Django 4.1.3 on 2023-02-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0043_alter_test_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeredcommontask",
            name="common_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="univ_app.commontask",
            ),
        ),
    ]
