# Generated by Django 4.1.1 on 2024-05-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("univ_app", "0045_alter_answeredinfotask_related_info_task"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="takentest",
            unique_together={("student", "related_test")},
        ),
    ]
